repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black
        exclude: '^test\/yaml\/resources\/expected_python_files\/'

      - id: isort
        name: isort
        language: python
        types: [python]
        entry: isort

      - id: flake8
        name: flake8
        language: python
        types: [python]
        entry: flake8
        exclude: E301

      - id: mypy
        name: mypy
        language: python
        types: [python]
        entry: mypy
