[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.pytest.ini_options]
testpaths = "tests"

[tool.coverage.run]
branch = true
source_pkgs = ["symeo_python"]

[tool.coverage.report]
fail_under = 80 # current code coverage
