version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Install dev requirements
          command: pip install -r requirements-dev.txt
      - run:
          name: Run test
          command: python -m pytest

workflows:
  build_test:
    jobs:
      - build_and_test
