version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    working_directory: ~/symeo-python
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirements.txt" }}-{{ checksum "~/symeo-python/requirements-dev.txt" }}
      - run:
          name: Install requirements in venv directory
          command: | 
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Install dev requirements in venv directory
          command: |
            source venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirements.txt" }}-{{ checksum "~/symeo-python/requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Run test with coverage
          command: |
            source venv/bin/activate
            coverage run -m pytest test
      - run:
          name: Display coverage
          command: |
            source venv/bin/activate
            coverage report
      - run:
          name: Build
          command: |
            source venv/bin/activate
            python -m build
      - save_cache:
          key: build-cache-{{ checksum "~/symeo-python/setup.py" }}
          paths:
            - "dist"
  #      - run:
  #          name: Build Sphinx html documentation
  #          command: sphinx-build -b html docs/source/ docs/build/html

  validate_configuration:
    executor: python/default
    working_directory: ~/symeo-python
    steps:
      - checkout
      - restore_cache:
              key: dependency-cache-{{ checksum "~/symeo-python/requirements.txt" }}-{{ checksum "~/symeo-python/requirements-dev.txt" }}
      - run:
          name: Install dev requirements in venv directory
          command: |
            source venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Install symeo-cli
          command: curl https://raw.githubusercontent.com/symeo-io/symeo-cli/main/scripts/install.sh | sudo bash
      - run:
          name: Validate
          command: |
            source venv/bin/activate
            symeo-cli validate --api-key $SYMEO_API_KEY

  release:
    executor: python/default
    working_directory: ~/symeo-python
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "~/symeo-python/setup.py" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirements.txt" }}-{{ checksum "~/symeo-python/requirements-dev.txt" }}
      - run:
          name: Install symeo-cli
          command: curl https://raw.githubusercontent.com/symeo-io/symeo-cli/main/scripts/install.sh | sudo bash
      - run:
          name: Release version
          command: |
            source venv/bin/activate
            symeo-cli start --api-key $SYMEO_API_KEY -- sh scripts/release.sh

workflows:
  build_test_release:
    jobs:
      - build_and_test:
          name: build_and_test
          filters:
            branches:
              only: /.*/
            tags:
              only: /^release-[0-9]+\.{1}[0-9]+\.{1}[0-9]+$/
      - validate_configuration:
          name: validate_configuration_production
          requires:
            - build_and_test
          context:
            - symeo-python
          filters:
            branches:
              only: main
            tags:
              only: /^release-[0-9]+\.{1}[0-9]+\.{1}[0-9]+$/
      - release:
          name: release
          requires:
            - build_and_test
            - validate_configuration_production
          context:
            - symeo-python
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-[0-9]+\.{1}[0-9]+\.{1}[0-9]+$/