version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirement.lock" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirement-dev.lock" }}
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirement.lock" }}
          paths:
            - requirement.txt
      - run:
          name: Install dev requirements
          command: pip install -r requirements-dev.txt
      - save_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirement-dev.lock" }}
          paths:
            - requirement-dev.txt
      - run:
          name: Run test with coverage
          command: coverage run -m pytest test
      - run:
          name: Display coverage
          command: coverage report
      - run:
          name: Build
          command: python -m build
      - save_cache:
          key: build-cache-{{ checksum "~/symeo-python/build.lock" }}
          paths:
            - /dist
  #      - run:
  #          name: Build Sphinx html documentation
  #          command: sphinx-build -b html docs/source/ docs/build/html
  release:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/build.lock" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-python/requirement-dev.lock" }}
      - run:
          name: Release version
          command: |
            version=$(echo $CIRCLE_TAG | cut -d '-' -f2)
            twine upload dist/symeo-python-$version.tar.gz dist/symeo_python-$version-py3-none-any.whl -u $PYPI_USERNAME -p $PYPI_PASSWORD

workflows:
  build_test_release:
    jobs:
      - build_and_test:
          name: build_and_test
      - release:
          name: release
          requires:
            - build_and_test
          filters:
            branches:
              only: main
            tags:
              only: /^release-[0-9]+(\.[0-9]+)+$/